apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: customers
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 12012
      targetPort: 12012
  type: ClusterIP
  