apiVersion: v1
kind: Service
metadata:
  name: customers
  namespace: customers
spec:
  type: ClusterIP
  selector:
    app: customers
  ports:
    - name: app
      port: 12012
      targetPort: 12012
    - name: probe
      port: 12112
      targetPort: 12112