apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
    - name: app
      port: 12012
      targetPort: 12012
    - name: probe
      port: 12112
      targetPort: 12112
