apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  serviceName: eureka
  replicas: 2
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: app
          image: jbazann/eureka:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JBAZANN_PEERS
              value: http://eureka-0.eureka:12012/eureka/,http://eureka-1.eureka:12012/eureka/
          ports:
            - name: app
              containerPort: 12012
            - name: probe
              containerPort: 12112
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 12112
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 15
          securityContext:
            privileged: false
      restartPolicy: Always
      