apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  type: ClusterIP
  selector:
    app: graylog
  ports:
    - name: app
      port: 12012
      targetPort: 12012
      appProtocol: http