apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-env
  namespace: graylog
data:
  GRAYLOG_ELASTICSEARCH_HOSTS: 'http://opensearch:12012'
  GRAYLOG_HTTP_BIND_ADDRESS: '0.0.0.0:12012'
  GRAYLOG_ROOT_PASSWORD_SHA2: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918' # admin
  GRAYLOG_PASSWORD_SECRET: 'somepasswordpepper'
  GRAYLOG_MONGODB_URI: 'mongodb://graylog:graylog@mongodb:12012/graylog'