apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cfg
  namespace: graylog
data:
  mongod.conf: |
    #   http://docs.mongodb.org/manual/reference/configuration-options/
    net:
      port: 12012
      bindIpAll: true
  mongo-init.js: |
    const username = process.env.MONGODB_USERNAME;
    const password = process.env.MONGODB_PASSWORD;
    const database = process.env.MONGODB_DATABASE
    
    db = db.getSiblingDB(database)
    db.createUser({
      user: username,
      pwd: password,
      roles: [
        { role: "readWrite", db: database },
        { role: "dbAdmin", db: database }
      ]
    });
