apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: graylog
spec:
  type: ClusterIP
  selector:
    app: opensearch
  ports:
    - protocol: TCP
      port: 12012
      targetPort: 12012
