apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy
  annotations:
    haproxy.org/path-rewrite: |
      /ui/(.*) /\1
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: app
          - path: /
            pathType: Exact
            backend:
              service:
                name: nodejs
                port:
                  name: app
          - path: /ui/
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  name: app
