spring:
  application:
    name: orders
  config:
    import: routes.yml # ignore warnings and see main project (tpdan) plugins
  data:
    mongodb:
      username: orders
      password: orders
      uri: mongodb://mongodb:12012/orders
      uuid-representation: standard
  rabbitmq:
    host: amqp-0
    port: 5671
    username: @jbazann.amqp.username@
    password: @jbazann.amqp.password@
    virtual-host: @jbazann.amqp.username@
    ssl:
      verify-hostname: false
      enabled: true


server:
  port: @jbazann.kube.main-port@

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:@jbazann.kube.main-port@/eureka/
    fetch-registry: false

management:
  server:
    port: @jbazann.kube.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health

jbazann:
  timeout:
    standard: @jbazann.timeout.standard@
  rabbit:
    exchanges:
      orders: @jbazann.rabbit.exchanges.orders@
    queues:
      saga: @jbazann.rabbit.queues.saga@
      operation: @jbazann.rabbit.queues.operation@