apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: orders
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: app
      port: 12012
      targetPort: 12012
      appProtocol: http