apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: orders
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: app
      port: 12012
      targetPort: 12012
    - name: probe
      port: 12112
      targetPort: 12112