spring:
  application:
    name: eureka
  profiles:
    active: @jbazann.spring-profiles@

server:
  port: @jbazann.eureka.port@

eureka:
  instance:
    hostname: @jbazann.eureka.server.host@
    metadata-map:
      region: @jbazann.eureka.region1@
  client:
    registerWithEureka: @jbazann.eureka.server.registerWithPeer@
    fetchRegistry: true
    region: @jbazann.eureka.region1@
    serviceUrl:
      defaultZone: @jbazann.eureka.server.defaultZone@

management:
  server:
    port: @jbazann.eureka.management-port@
  endpoints:
    web:
      exposure:
        include: httpexchanges,health