apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-cfg
  namespace: metrics
data:
  prometheus-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:12012