apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: metrics
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: app
      port: 12012
      targetPort: 12012
      appProtocol: http