apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - name: app
      port: 12012
      targetPort: 12012
      appProtocol: https
    - name: probe
      port: 12112
      targetPort: 12112